name: probation
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  line_icons: ^0.2.0
  http: ^0.12.0+2

  carousel_slider: ^1.3.0
  modal_progress_hud: ^0.1.3 
  flutter_secure_storage: ^3.3.1+1

  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - assets/images/alfabizz.jpeg
  - assets/images/food1.jpg
  - assets/images/kopi.jpeg



